/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Cookie-authenticated CSRF recovery; requires matching Origin or Sec-Fetch-Site same-origin and rejects foreign Origin. */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bounded content-free operational summary for the console landing page. */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Content-free operational history ordered by start time and immutable request id. */
        get: operations["listOperationalRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOperationalAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Desired settings for export plus effective runtime settings; never TLS key contents. */
        get: operations["getAdminSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolve omitted fields from observed settings, validate and bind the normalized result to a short-lived single-use settings-purpose token. */
        post: operations["planAdminSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically consume plan, persist desired settings and audit; effective runtime settings remain unchanged until restart. */
        post: operations["applyAdminSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        get: operations["listResources"];
        put?: never;
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{kind}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        get: operations["getResource"];
        put: operations["replaceResource"];
        post?: never;
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSecretMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSecretMetadata"];
        put: operations["setSecret"];
        post?: never;
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-tokens/{name}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-tokens/{name}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-tokens/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentTokenStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{name}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testProviderConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminSettingsState: {
            desired: components["schemas"]["resolved"];
            effective: components["schemas"]["resolved"];
            restartRequired: boolean;
        };
        AdminSettingsPlan: {
            desired: components["schemas"]["resolved"];
            changedFields: ("publicOrigin" | "listen" | "transport" | "trustedProxyCidrs" | "tlsCertificatePath" | "tlsPrivateKeyPath" | "idleSeconds" | "absoluteSeconds" | "globalAttemptsPerMinute" | "globalBurst" | "clientAttemptsPerMinute" | "clientBurst" | "maxClientEntries" | "clientIdleSeconds" | "argonMemoryKiB" | "argonIterations" | "failedLoginRetentionSeconds")[];
            planToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        AdminSettingsApplyResult: {
            /** @constant */
            applied: true;
            /** Format: date-time */
            appliedAt: string;
            settings: components["schemas"]["AdminSettingsState"];
        };
        Login: {
            username: string;
            /** @description Maximum 1024 UTF-8 bytes enforced by server */
            password: string;
        };
        Admin: {
            /** Format: uuid */
            id: string;
            username: string;
        };
        SessionContext: {
            admin: components["schemas"]["Admin"];
            /** @description Kept in SPA memory and sent as X-CSRF-Token */
            csrfToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Overview: {
            resourceCounts: {
                [key: string]: number;
            };
            requests24h: {
                total: number;
                success: number;
                error: number;
            };
            activeCooldowns: number;
            recentRequests: {
                /** Format: uuid */
                id: string;
                requestedAlias: string;
                /** Format: date-time */
                startedAt: string;
                /** Format: date-time */
                completedAt?: string | null;
                /** @enum {string|null} */
                outcome?: "success" | "error" | "partial" | "cancelled" | "indeterminate" | null;
                httpStatus?: number | null;
                durationMs?: number | null;
                attempts: number;
            }[];
            /** Format: date-time */
            generatedAt: string;
        };
        OperationalRequestPage: {
            items: components["schemas"]["OperationalRequest"][];
            nextCursor?: string | null;
        };
        OperationalRequest: {
            id: string;
            requestedAlias: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            /** @enum {string|null} */
            outcome?: "success" | "error" | "partial" | "cancelled" | "indeterminate" | null;
            httpStatus?: number | null;
            inputTokens?: number | null;
            outputTokens?: number | null;
            ttftMillis?: number | null;
            durationMillis?: number | null;
            attempts: number;
        };
        OperationalAttempt: {
            sequence: number;
            destinationID?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            /** @enum {string} */
            outcome: "success" | "error" | "partial" | "cancelled" | "indeterminate";
            errorClass?: string | null;
            providerStatus?: number | null;
            providerRequestID?: string | null;
            retryable: boolean;
            fallbackReason?: string | null;
        };
        Resource: components["schemas"]["resource"];
        ResourcePage: {
            items: components["schemas"]["resource"][];
            nextCursor?: string | null;
        };
        SecretMetadata: {
            name: string;
            resourceVersion: number;
            /** @description Non-reversible display fingerprint */
            fingerprint?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentTokenStatus: {
            /** @enum {string} */
            state: "unissued" | "active" | "expired" | "revoked";
            prefix?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        Validation: {
            valid: boolean;
            issues: components["schemas"]["Issue"][];
        };
        Issue: {
            /** @enum {unknown} */
            severity: "error" | "warning";
            code: string;
            path: string;
            message: string;
        };
        Plan: {
            valid: boolean;
            /** @description Opaque short-lived precondition token required by apply; never contains secret values. */
            planToken: string;
            /** Format: date-time */
            expiresAt: string;
            changes: {
                /** @enum {unknown} */
                operation: "create" | "update" | "noop" | "delete";
                kind: string;
                name: string;
            }[];
        };
        ApplyResult: {
            /** @constant */
            applied: true;
            /** Format: date-time */
            appliedAt: string;
            changes: {
                /** @enum {unknown} */
                operation: "create" | "update" | "noop" | "delete";
                kind: string;
                name: string;
            }[];
        };
        Error: {
            error: {
                code: string;
                message: string;
                requestId: string;
                field?: string | null;
                /** @default false */
                retryable: boolean;
            };
        };
        spec: {
            publicOrigin?: string;
            /** @default 127.0.0.1:8080 */
            listen: string;
            /**
             * @default loopback-http
             * @enum {unknown}
             */
            transport: "loopback-http" | "direct-tls" | "proxy-tls";
            /** @default [] */
            trustedProxyCidrs: string[];
            /** @default  */
            tlsCertificatePath: string;
            /** @default  */
            tlsPrivateKeyPath: string;
            /** @default 1800 */
            idleSeconds: number;
            /** @default 43200 */
            absoluteSeconds: number;
            /** @default 30 */
            globalAttemptsPerMinute: number;
            /** @default 5 */
            globalBurst: number;
            /** @default 5 */
            clientAttemptsPerMinute: number;
            /** @default 3 */
            clientBurst: number;
            /** @default 1024 */
            maxClientEntries: number;
            /** @default 900 */
            clientIdleSeconds: number;
            /**
             * @description Retention duration for aggregate failed-login statistics; 0 means unlimited time retention.
             * @default 86400
             */
            failedLoginRetentionSeconds: number;
            /** @default 19456 */
            argonMemoryKiB: number;
            /** @default 2 */
            argonIterations: number;
        };
        document: {
            /** @constant */
            apiVersion: "modelcairn.io/v1alpha1";
            /** @constant */
            kind: "AdminSettings";
            resourceVersion?: number;
            spec: components["schemas"]["spec"];
        };
        update: components["schemas"]["document"] & unknown;
        resolved: components["schemas"]["update"] & {
            spec?: unknown;
        };
        name: string;
        tombstoneMetadata: {
            name: components["schemas"]["name"];
            /** Format: uuid */
            readonly uid?: string;
            readonly resourceVersion?: number;
        };
        tombstone: {
            /** @enum {unknown} */
            kind: "Provider" | "ProviderAccount" | "ProviderConnection" | "Credential" | "Egress" | "Model" | "Destination" | "Strategy" | "Route" | "AgentToken";
            /** @constant */
            state: "absent";
            metadata: components["schemas"]["tombstoneMetadata"];
        };
        metadata: {
            name: components["schemas"]["name"];
            displayName?: string;
            description?: string;
            /** Format: uuid */
            readonly uid?: string;
            readonly resourceVersion?: number;
        };
        base: {
            /**
             * @default present
             * @constant
             */
            state: "present";
            metadata: components["schemas"]["metadata"];
        };
        provider: components["schemas"]["base"] & {
            /** @constant */
            kind: "Provider";
            state?: unknown;
            metadata: unknown;
            spec: Record<string, never>;
        };
        ref: {
            name: components["schemas"]["name"];
        };
        providerAccount: components["schemas"]["base"] & {
            /** @constant */
            kind: "ProviderAccount";
            state?: unknown;
            metadata: unknown;
            spec: {
                providerRef: components["schemas"]["ref"];
            };
        };
        connection: components["schemas"]["base"] & {
            /** @constant */
            kind: "ProviderConnection";
            state?: unknown;
            metadata: unknown;
            spec: {
                providerRef: components["schemas"]["ref"];
                /** Format: uri */
                baseUrl: string;
                /** @enum {string} */
                adapter: "openai-chat-v1";
                /** @default false */
                allowPrivateNetwork: boolean;
                /** @default true */
                enabled: boolean;
            };
        };
        credential: components["schemas"]["base"] & {
            /** @constant */
            kind: "Credential";
            state?: unknown;
            metadata: unknown;
            spec: {
                providerAccountRef: components["schemas"]["ref"];
                egressRef: components["schemas"]["ref"];
                secretRef: components["schemas"]["ref"];
                /** @default true */
                enabled: boolean;
            };
        };
        egress: components["schemas"]["base"] & {
            /** @constant */
            kind: "Egress";
            state?: unknown;
            metadata: unknown;
            spec: {
                /** @constant */
                type: "direct";
                /** @default true */
                enabled: boolean;
            };
        };
        model: components["schemas"]["base"] & {
            /** @constant */
            kind: "Model";
            state?: unknown;
            metadata: unknown;
            spec: {
                connectionRef: components["schemas"]["ref"];
                providerModelId: string;
                capabilities: ("text" | "stream" | "tools" | "parallel-tools" | "developer-role" | "json-schema" | "logprobs")[];
                /** @default true */
                enabled: boolean;
            };
        };
        destination: components["schemas"]["base"] & {
            /** @constant */
            kind: "Destination";
            state?: unknown;
            metadata: unknown;
            spec: {
                modelRef: components["schemas"]["ref"];
                credentialRef: components["schemas"]["ref"];
                /** @default true */
                enabled: boolean;
                /** @default 100 */
                weight: number;
            };
        };
        strategy: components["schemas"]["base"] & {
            /** @constant */
            kind: "Strategy";
            state?: unknown;
            metadata: unknown;
            spec: {
                destinations: components["schemas"]["ref"][];
                /** @default 3 */
                maxAttempts: number;
                /** @default 60000 */
                attemptTimeoutMs: number;
                /** @default 120000 */
                totalTimeoutMs: number;
            };
        };
        route: components["schemas"]["base"] & {
            /** @constant */
            kind: "Route";
            state?: unknown;
            metadata: unknown;
            spec: {
                modelAlias: string;
                strategyRef: components["schemas"]["ref"];
                /** @default true */
                enabled: boolean;
            };
        };
        agentToken: components["schemas"]["base"] & {
            /** @constant */
            kind: "AgentToken";
            state?: unknown;
            metadata: unknown;
            spec: {
                allowedRouteRefs: components["schemas"]["ref"][];
                /** Format: date-time */
                expiresAt?: string | null;
                /** @default true */
                enabled: boolean;
            };
        };
        resource: components["schemas"]["tombstone"] | components["schemas"]["provider"] | components["schemas"]["providerAccount"] | components["schemas"]["connection"] | components["schemas"]["credential"] | components["schemas"]["egress"] | components["schemas"]["model"] | components["schemas"]["destination"] | components["schemas"]["strategy"] | components["schemas"]["route"] | components["schemas"]["agentToken"];
        /** ModelCairn declarative configuration */
        "modelcairn-config-v1alpha1.schema": {
            /** @constant */
            apiVersion: "modelcairn.io/v1alpha1";
            /** @constant */
            kind: "Configuration";
            resources: components["schemas"]["resource"][];
            $defs: {
                name: string;
                metadata: {
                    name: components["schemas"]["name"];
                    displayName?: string;
                    description?: string;
                    /** Format: uuid */
                    readonly uid?: string;
                    readonly resourceVersion?: number;
                };
                tombstoneMetadata: {
                    name: components["schemas"]["name"];
                    /** Format: uuid */
                    readonly uid?: string;
                    readonly resourceVersion?: number;
                };
                ref: {
                    name: components["schemas"]["name"];
                };
                base: {
                    /**
                     * @default present
                     * @constant
                     */
                    state: "present";
                    metadata: components["schemas"]["metadata"];
                };
                provider: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Provider";
                    state?: unknown;
                    metadata: unknown;
                    spec: Record<string, never>;
                };
                providerAccount: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "ProviderAccount";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        providerRef: components["schemas"]["ref"];
                    };
                };
                connection: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "ProviderConnection";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        providerRef: components["schemas"]["ref"];
                        /** Format: uri */
                        baseUrl: string;
                        /** @enum {string} */
                        adapter: "openai-chat-v1";
                        /** @default false */
                        allowPrivateNetwork: boolean;
                        /** @default true */
                        enabled: boolean;
                    };
                };
                credential: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Credential";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        providerAccountRef: components["schemas"]["ref"];
                        egressRef: components["schemas"]["ref"];
                        secretRef: components["schemas"]["ref"];
                        /** @default true */
                        enabled: boolean;
                    };
                };
                egress: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Egress";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        /** @constant */
                        type: "direct";
                        /** @default true */
                        enabled: boolean;
                    };
                };
                model: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Model";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        connectionRef: components["schemas"]["ref"];
                        providerModelId: string;
                        capabilities: ("text" | "stream" | "tools" | "parallel-tools" | "developer-role" | "json-schema" | "logprobs")[];
                        /** @default true */
                        enabled: boolean;
                    };
                };
                destination: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Destination";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        modelRef: components["schemas"]["ref"];
                        credentialRef: components["schemas"]["ref"];
                        /** @default true */
                        enabled: boolean;
                        /** @default 100 */
                        weight: number;
                    };
                };
                strategy: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Strategy";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        destinations: components["schemas"]["ref"][];
                        /** @default 3 */
                        maxAttempts: number;
                        /** @default 60000 */
                        attemptTimeoutMs: number;
                        /** @default 120000 */
                        totalTimeoutMs: number;
                    };
                };
                route: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "Route";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        modelAlias: string;
                        strategyRef: components["schemas"]["ref"];
                        /** @default true */
                        enabled: boolean;
                    };
                };
                agentToken: components["schemas"]["base"] & {
                    /** @constant */
                    kind: "AgentToken";
                    state?: unknown;
                    metadata: unknown;
                    spec: {
                        allowedRouteRefs: components["schemas"]["ref"][];
                        /** Format: date-time */
                        expiresAt?: string | null;
                        /** @default true */
                        enabled: boolean;
                    };
                };
                tombstone: {
                    /** @enum {unknown} */
                    kind: "Provider" | "ProviderAccount" | "ProviderConnection" | "Credential" | "Egress" | "Model" | "Destination" | "Strategy" | "Route" | "AgentToken";
                    /** @constant */
                    state: "absent";
                    metadata: components["schemas"]["tombstoneMetadata"];
                };
                resource: components["schemas"]["tombstone"] | components["schemas"]["provider"] | components["schemas"]["providerAccount"] | components["schemas"]["connection"] | components["schemas"]["credential"] | components["schemas"]["egress"] | components["schemas"]["model"] | components["schemas"]["destination"] | components["schemas"]["strategy"] | components["schemas"]["route"] | components["schemas"]["agentToken"];
            };
        };
    };
    responses: {
        /** @description Login admission denied; retry after the indicated number of seconds. */
        RateLimited: {
            headers: {
                "Retry-After": string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Structured error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource with ETag header */
        Resource: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["resource"];
            };
        };
        /** @description Metadata only; never the secret value */
        SecretMetadata: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SecretMetadata"];
            };
        };
        /** @description Validation result */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Validation"];
            };
        };
        /** @description Redacted ordered changes */
        Plan: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Plan"];
            };
        };
        /** @description Redacted result of the atomic apply */
        ApplyResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApplyResult"];
            };
        };
    };
    parameters: {
        Kind: "providers" | "provider-accounts" | "provider-connections" | "credentials" | "egresses" | "models" | "destinations" | "strategies" | "routes" | "agent-tokens";
        Name: string;
        /** @description Single strong quoted positive resource version. Missing returns 428, malformed (including wildcard or lists) 400, stale 412. */
        IfMatch: string;
        /** @description Omit only when creating a new secret; replacing an existing secret requires its current strong ETag. */
        IfMatchOptional: string;
        /** @description Opaque token returned by the matching plan endpoint; binds operation purpose, normalized desired document, observed revision and expiry. Configuration and settings tokens are not interchangeable. */
        PlanToken: string;
    };
    requestBodies: {
        /** @description At most 64 KiB; resourceVersion is the observed desired settings revision. Omitted spec fields preserve their current values. */
        AdminSettingsUpdate: {
            content: {
                "application/json": components["schemas"]["update"];
                "application/yaml": components["schemas"]["update"];
            };
        };
        Configuration: {
            content: {
                "application/json": components["schemas"]["modelcairn-config-v1alpha1.schema"];
                "application/yaml": components["schemas"]["modelcairn-config-v1alpha1.schema"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Session created; token is also returned by session/me after reload */
            200: {
                headers: {
                    /** @description mc_session with HttpOnly, SameSite=Strict, Path=/ and Secure on HTTPS */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource totals, last-24-hour outcomes, active cooldown count, and at most five recent requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listOperationalRequests: {
        parameters: {
            query?: {
                outcome?: "success" | "error" | "partial" | "cancelled" | "indeterminate";
                alias?: string;
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalRequestPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listOperationalAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description At most 32 attempts ordered by sequence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OperationalAttempt"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consistent desired and effective settings snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsState"];
                };
            };
        };
    };
    planAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AdminSettingsUpdate"];
        responses: {
            /** @description Validated desired settings; no persistence or restart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsPlan"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    applyAdminSettings: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque token returned by the matching plan endpoint; binds operation purpose, normalized desired document, observed revision and expiry. Configuration and settings tokens are not interchangeable. */
                "X-ModelCairn-Plan-Token": components["parameters"]["PlanToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AdminSettingsUpdate"];
        responses: {
            /** @description Transaction-faithful result; no-op also consumes the plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsApplyResult"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    listResources: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page ordered by immutable uid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePage"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["resource"];
            };
        };
        responses: {
            201: components["responses"]["Resource"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
            404: components["responses"]["Error"];
        };
    };
    replaceResource: {
        parameters: {
            query?: never;
            header: {
                /** @description Single strong quoted positive resource version. Missing returns 428, malformed (including wildcard or lists) 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["resource"];
            };
        };
        responses: {
            200: components["responses"]["Resource"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            428: components["responses"]["Error"];
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header: {
                /** @description Single strong quoted positive resource version. Missing returns 428, malformed (including wildcard or lists) 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            428: components["responses"]["Error"];
        };
    };
    validateConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Configuration"];
        responses: {
            200: components["responses"]["Validation"];
            400: components["responses"]["Error"];
        };
    };
    planConfiguration: {
        parameters: {
            query?: {
                allowDelete?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Configuration"];
        responses: {
            200: components["responses"]["Plan"];
            400: components["responses"]["Error"];
        };
    };
    applyConfiguration: {
        parameters: {
            query?: {
                allowDelete?: boolean;
            };
            header: {
                /** @description Opaque token returned by the matching plan endpoint; binds operation purpose, normalized desired document, observed revision and expiry. Configuration and settings tokens are not interchangeable. */
                "X-ModelCairn-Plan-Token": components["parameters"]["PlanToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Configuration"];
        responses: {
            200: components["responses"]["ApplyResult"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    exportConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical configuration without secret values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["modelcairn-config-v1alpha1.schema"];
                };
            };
        };
    };
    listSecretMetadata: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded page of redacted secret metadata ordered by immutable secret id. Cursor is an opaque continuation after the last id; pages are not a cross-request snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SecretMetadata"][];
                        nextCursor?: string | null;
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getSecretMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SecretMetadata"];
            404: components["responses"]["Error"];
        };
    };
    setSecret: {
        parameters: {
            query?: never;
            header?: {
                /** @description Omit only when creating a new secret; replacing an existing secret requires its current strong ETag. */
                "If-Match"?: components["parameters"]["IfMatchOptional"];
            };
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Server enforces 8–16384 UTF-8 bytes; JSON Schema length counts characters. */
                    value: string;
                };
            };
        };
        responses: {
            200: components["responses"]["SecretMetadata"];
            201: components["responses"]["SecretMetadata"];
            400: components["responses"]["Error"];
            412: components["responses"]["Error"];
            428: components["responses"]["Error"];
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header: {
                /** @description Single strong quoted positive resource version. Missing returns 428, malformed (including wildcard or lists) 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            428: components["responses"]["Error"];
        };
    };
    issueAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token value returned exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description One-time intentional delivery to the authenticated issuer; never logged or recoverable later. */
                        readonly token: string;
                        tokenStatus: components["schemas"]["AgentTokenStatus"];
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    revokeAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked immediately for new requests */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    getAgentTokenStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe credential lifecycle metadata; never a bearer or verifier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokenStatus: components["schemas"]["AgentTokenStatus"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    publishStrategy: {
        parameters: {
            query?: never;
            header: {
                /** @description Single strong quoted positive resource version. Missing returns 428, malformed (including wildcard or lists) 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            428: components["responses"]["Error"];
        };
    };
    testProviderConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted diagnostic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        latencyMs: number;
                        code?: string | null;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
}
