import { FormEvent, useEffect, useState } from "react";
import { api, OperationalAttempt, OperationalRequest } from "./api/client";

type Filters={outcome?:string;alias?:string;from?:string;to?:string};
const outcomeLabels:Record<string,string>={success:"Correcta",error:"Error",partial:"Parcial",cancelled:"Cancelada",indeterminate:"Indeterminada"};
export default function Activity(){
  const [items,setItems]=useState<OperationalRequest[]>([]);const [cursor,setCursor]=useState<string|null>();const [filters,setFilters]=useState<Filters>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=(next?:string,desired=filters)=>{setLoading(true);setError("");api.listRequests({...desired,cursor:next}).then(page=>{setItems(current=>next?[...current,...page.items]:page.items);setCursor(page.nextCursor);}).catch(()=>setError("No pudimos cargar la actividad.")).finally(()=>setLoading(false));};
  useEffect(()=>load(undefined,{}),[]);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const value:Filters={outcome:String(data.get("outcome")||"")||undefined,alias:String(data.get("alias")||"")||undefined};for(const key of ["from","to"] as const){const raw=String(data.get(key)||"");if(raw)value[key]=new Date(raw).toISOString();}setFilters(value);load(undefined,value);}
  return <section aria-labelledby="activity-title"><p className="eyebrow">DIAGNÓSTICO</p><h1 id="activity-title">Actividad</h1><p className="lede">Solicitudes e intentos sin prompts ni respuestas. Las horas se muestran en tu zona local.</p><form className="activity-filters" onSubmit={submit}><label>Resultado<select name="outcome"><option value="">Todos</option><option value="success">Correctas</option><option value="error">Errores</option><option value="partial">Parciales</option><option value="cancelled">Canceladas</option><option value="indeterminate">Indeterminadas</option></select></label><label>Alias<input name="alias" maxLength={128} placeholder="assistant"/></label><label>Desde<input name="from" type="datetime-local"/></label><label>Hasta<input name="to" type="datetime-local"/></label><button>Aplicar filtros</button></form>{error&&<div className="form-error" role="alert">{error}</div>}{items.length > 0 && <div className="activity-table" role="table" aria-label="Solicitudes"><div className="activity-header" role="row"><span>Hora y alias</span><span>Resultado</span><span>Latencia</span><span>Tokens</span><span>Intentos</span></div>{items.map(item=><RequestRow key={item.id} item={item}/>)}</div>}{!loading&&items.length===0&&<div className="list-empty">No hay solicitudes para estos filtros.</div>}{loading?<div className="loading" role="status"><span className="spinner"/>Cargando actividad…</div>:cursor&&<button className="load-more" onClick={()=>load(cursor)}>Cargar más</button>}</section>;
}

function RequestRow({item}:{item:OperationalRequest}) {
  const [open,setOpen]=useState(false); const [attempts,setAttempts]=useState<OperationalAttempt[]|null>(null); const [failed,setFailed]=useState(false);
  function load(){setFailed(false);setAttempts(null);api.listAttempts(item.id).then(value=>setAttempts(value.items)).catch(()=>setFailed(true));}
  function toggle(){const next=!open;setOpen(next);if(next&&!attempts&&!failed)load();}
  return <div className="request-wrap"><button className="request-row" role="row" onClick={toggle} aria-expanded={open}><span><strong>{item.requestedAlias}</strong><small>{new Date(item.startedAt).toLocaleString()}</small></span><span className={`outcome ${item.outcome??"pending"}`}>{item.outcome?(outcomeLabels[item.outcome]??"Otro resultado"):"En curso"}{item.httpStatus?` · ${item.httpStatus}`:""}</span><span>{item.durationMillis==null?"—":`${item.durationMillis} ms`}{item.ttftMillis==null?"":<small>TTFT {item.ttftMillis} ms</small>}</span><span>{(item.inputTokens??0)+(item.outputTokens??0)||"—"}</span><span>{item.attempts}</span></button>{open&&<div className="attempts">{failed?<span>No se pudieron cargar los intentos. <button onClick={load}>Reintentar</button></span>:attempts===null?<span>Cargando intentos…</span>:attempts.length===0?<span>Sin intentos registrados.</span>:attempts.map(attempt=><article key={attempt.sequence}><strong>Intento {attempt.sequence}</strong><span className={`outcome ${attempt.outcome}`}>{outcomeLabels[attempt.outcome]??"Otro resultado"}</span><span>{attempt.providerStatus??"sin HTTP"}</span><span>{attempt.errorClass??attempt.fallbackReason??"—"}</span>{attempt.retryable&&<small>Permitió fallback</small>}</article>)}</div>}</div>;
}
