import { FormEvent, useEffect, useState } from "react";
import { api, APIError, SecretMetadata } from "./api/client";

export default function Secrets() {
  const from = new URLSearchParams(window.location.hash.split("?")[1] ?? "").get("from");
  const back = from?.startsWith("#/providers/") ? from : "#/providers";
  const [items,setItems]=useState<SecretMetadata[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const load=()=>{setLoading(true);api.listSecrets().then((page)=>setItems(page.items)).catch(()=>setMessage("No pudimos cargar los secretos.")).finally(()=>setLoading(false));};
  useEffect(load,[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const input=form.elements.namedItem("value") as HTMLInputElement;setMessage("");try{await api.saveSecret(String(data.get("name")),String(data.get("value")));input.value="";form.reset();setMessage("Secreto guardado. Su valor ya no puede recuperarse desde la consola.");load();}catch(reason){setMessage(reason instanceof APIError?`No se pudo guardar (${reason.code}).`:"No se pudo guardar el secreto.");}}
  async function remove(item:SecretMetadata){if(!confirm(`¿Eliminar ${item.name}? Solo será posible si ninguna credencial lo utiliza.`))return;try{await api.deleteSecret(item.name,item.resourceVersion);load();}catch{setMessage("El secreto está en uso o cambió desde que abriste esta pantalla.");}}
  return <section aria-labelledby="secrets-title"><a className="catalog-back" href={back}>← Volver a API keys</a><h1 id="secrets-title">Claves guardadas</h1><p className="lede">Guarda aquí las claves de tus proveedores. Se cifran en el nodo principal; después se vinculan al proveedor desde sus opciones avanzadas. La huella es un identificador no reversible para distinguir claves sin mostrar su valor.</p><form className="secret-form" onSubmit={save}><label>Nombre<input name="name" required pattern="[a-z][a-z0-9-]{0,62}" placeholder="provider-key"/></label><label>API key o secreto<input name="value" type="password" required minLength={8} maxLength={16384} autoComplete="off"/></label><button>Guardar o reemplazar</button></form>{message&&<div className="notice" role="status">{message}</div>}{loading?<div className="loading" role="status"><span className="spinner"/>Cargando secretos…</div>:<div className="secret-list">{items.length===0?<div className="list-empty">Todavía no hay secretos.</div>:items.map((item)=><article key={item.name}><div><h2>{item.name}</h2><p>Huella: <code>{item.fingerprint??"no disponible"}</code></p><small>Actualizado {new Date(item.updatedAt).toLocaleString()}</small></div><button className="danger" onClick={()=>remove(item)}>Eliminar</button></article>)}</div>}</section>;
}
